### ISSUE TITLE
[S2 - PBI4] Membuat halaman menampilkan sertifikat

### ISSUE THREAD

**Issue by AlamAdhiyatama** [SI-RPL-2022/SI4302_C_GIATKAYA#10]

**Comment by AlamAdhiyatama** [comment]
![image](https://user-images.githubusercontent.com/92213641/164568707-58f62133-bba7-4a06-887b-bef8cdd3d45c.png)
<img width="425" alt="image" src="https://user-images.githubusercontent.com/92213641/164568765-eb9577a6-00f5-4e08-acb4-05be12603382.png">
![image](https://user-images.githubusercontent.com/92213641/164568792-544d94d5-0621-4e45-8c25-e3618eae5ed3.png)

**Comment by ekkynovrizalam** [comment]
ditambahkan fitur search

**Comment by rakhabatara** [comment]
https://user-images.githubusercontent.com/92209018/170902848-c95cd54f-25af-4217-9b35-fbba3d9685ed.mp4
