### ISSUE TITLE
[S2 - PBI5] Membuat halaman form untuk mengajukan pinjaman dana

### ISSUE THREAD

**Issue by AlamAdhiyatama** [SI-RPL-2022/SI4302_C_GIATKAYA#11]

**Comment by AlamAdhiyatama** [comment]
![image](https://user-images.githubusercontent.com/92213641/164570979-06d3a222-42c0-4382-b1f6-f2d5b136aac1.png)
<img width="355" alt="image" src="https://user-images.githubusercontent.com/92213641/164571091-b79b06f2-52bc-495a-abc5-4e0d980ff93b.png">
![image](https://user-images.githubusercontent.com/92213641/164571111-a64d832f-34cd-491a-81cc-cdf705da432a.png)

**Comment by ekkynovrizalam** [comment]
1. UI untuk mengisi data dirinya seperti apa?
2. Kemudian bagian penentuan dana pinjaman itu apakah dinamis menggunakan javascript? Misalnya dropdownnya diganti menjadi value lain akan di kalkulasi seketika?

**Comment by rakhabatara** [comment]
https://user-images.githubusercontent.com/92209018/174854242-defc0d20-8670-49b2-be9e-73d6e8a248e1.mp4
