### ISSUE TITLE
[S3 - PBI2] Membuat laman akses info kerja

### ISSUE THREAD

**Issue by AlamAdhiyatama** [SI-RPL-2022/SI4302_C_GIATKAYA#13]

**Comment by AlamAdhiyatama** [comment]
![image](https://user-images.githubusercontent.com/92213641/171753356-29e5ffa4-fa96-4a53-a314-e86eb18d4144.png)
<img width="354" alt="image" src="https://user-images.githubusercontent.com/92213641/171753412-8383b3ba-70cb-469c-87ba-cc12e6ffa9db.png">
![image](https://user-images.githubusercontent.com/92213641/171753432-1cf8aee1-2166-4446-af6a-7cf34f9fd555.png)

**Comment by naufalavi** [comment]
https://user-images.githubusercontent.com/92262039/174959923-baeba5e0-a76e-44a4-ad7b-f2dbfbac1390.mp4
