### ISSUE TITLE
[S3 - PBI3] Membuat laman Landing Page

### ISSUE THREAD

**Issue by AlamAdhiyatama** [SI-RPL-2022/SI4302_C_GIATKAYA#14]

**Comment by AlamAdhiyatama** [comment]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/92213641/171753511-a9c6c5fe-d1bc-4d6b-b3ac-23e810801e24.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/92213641/171753533-cb9d5478-b367-4e06-b120-d023f057e8db.png">

**Comment by FajarSidik02** [comment]
https://user-images.githubusercontent.com/92220858/174849986-fba2a2e9-db8f-4292-b8bc-fb45abc37cb0.mp4
