### ISSUE TITLE
[S3 - PBI4] Membuat laman untuk pengembalian dana atau hutang dari pinjaman dana

### ISSUE THREAD

**Issue by AlamAdhiyatama** [SI-RPL-2022/SI4302_C_GIATKAYA#15]

**Comment by AlamAdhiyatama** [comment]
![image](https://user-images.githubusercontent.com/92213641/171753949-0e24f7e3-91fa-4d37-af3d-86fd36908cf1.png)
<img width="355" alt="image" src="https://user-images.githubusercontent.com/92213641/171753987-7ed4024e-340f-4199-b524-0604772481d5.png">

![image](https://user-images.githubusercontent.com/92213641/171754014-b50fb8a9-ccc6-4b79-a9e1-84fd3ea2122f.png)

**Comment by AlamAdhiyatama** [comment]
Tambahan Alur setelah list tagihan :
1. User klik tombol untuk melakukan pembayaran
2. Muncul halaman summary pembayaran dan ada tombol bayar
3. ketika sudah bayar status berubah paid

**Comment by rakhabatara** [comment]
https://user-images.githubusercontent.com/92209018/174854595-8498f2ca-ef73-46b0-9692-b5b075072e5f.mp4
