### ISSUE TITLE
[S2 - PBI2] Membuat halaman Training Skill

### ISSUE THREAD

**Issue by AlamAdhiyatama** [SI-RPL-2022/SI4302_C_GIATKAYA#8]

**Comment by AlamAdhiyatama** [comment]
![image](https://user-images.githubusercontent.com/92213641/164568396-1a0a29ce-c005-4b96-b14e-354f0e3759ce.png)
<img width="424" alt="image" src="https://user-images.githubusercontent.com/92213641/164568487-4a02bd4c-af3f-443e-9a90-b1a818d4f5aa.png">
![image](https://user-images.githubusercontent.com/92213641/164568518-66da4d43-1699-4377-bc10-5a56cb8b0857.png)

**Comment by FajarSidik02** [comment]
Ditambahkan mockup langsung ke pelatihan (video / bacaan)

**Comment by ekkynovrizalam** [comment]
ditambahkan keterangan keikutsertaan setelah klik pelatihan tsb
