### ISSUE TITLE
[S2 - PBI3] Membuat laman CRUD certification (Admin)

### ISSUE THREAD

**Issue by AlamAdhiyatama** [SI-RPL-2022/SI4302_C_GIATKAYA#9]

**Comment by AlamAdhiyatama** [comment]
![image](https://user-images.githubusercontent.com/92213641/164570394-063c957a-93dd-48f6-b290-3eb72f368c22.png)
<img width="427" alt="image" src="https://user-images.githubusercontent.com/92213641/164570520-7bd77017-8bb8-4828-97c8-38b032a0e195.png">
<img width="427" alt="image" src="https://user-images.githubusercontent.com/92213641/164570544-5c82ecfc-912c-447f-bf5e-92816608055c.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/92213641/164570586-084ac53f-1b82-4043-8eee-1dfb242b884b.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/92213641/164570600-afa4ef3d-4d16-4916-8537-d2e2b30c7c93.png">
![image](https://user-images.githubusercontent.com/92213641/164570640-2d6621cc-822e-465e-a7dd-5c55202275a7.png)

**Comment by naufalavi** [comment]
https://user-images.githubusercontent.com/92262039/170912231-f04efb89-5b88-4246-8600-f304f0c73c6a.mp4

**Comment by naufalavi** [comment]
https://user-images.githubusercontent.com/92262039/170915517-0570914c-a562-4b67-842a-45ff5eb4e4f6.mp4
